core/urls.py
from django.urls import path
from core.views import product_list_view,category_list_view,product_category_list_view,seller_list_view,seller_detail_view,product_detail_view,tag_list, ajax_add_review,search_view,index

app_name= "core"

urlpatterns = [

    #HomePage
    path('',index,name='index'),

    #Products
    path("products/",product_list_view,name="product-list"),
    path("products/<pid>",product_detail_view,name="product-detail"),

    #Categories
    path("category/",category_list_view,name="category-list"),
    path("category/<cid>/",product_category_list_view,name="product-category-list"),
    
    #Seller
    path("seller/",seller_list_view,name="seller-list"),
    path("seller/<sid>/",seller_detail_view,name="seller-detail"),

    #Tags
    path("products/tag/<slug:tag_slug>/",tag_list,name="tag"),

    #Reviews
    path("ajax-add-review/<pid>/", ajax_add_review, name="ajax-add-review"),

    #Search
    path("search/",search_view, name="search")

]                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

ecommerceprojet2/urls.py
from django.contrib import admin
from django.urls import path ,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)      

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)      

userauths/urls.py
from django.urls import path
from userauths import views

app_name= "userauths"

urlpatterns = [
    path("sign-up/",views.register_view,name="sign-up"),
    path("sign-in/",views.login_view,name="sign-in"), 
    path("sign-out/",views.logout_view,name="sign-out"),
    path('profile/', views.profile, name='profile'),
    path('contact/', views.contact, name="contact"),
] 

templates/partials/base.html
<!-- /*
* Bootstrap 5
* Template Name: Furni
* Template Author: Untree.co
* Template URI: https://untree.co/
* License: https://creativecommons.org/licenses/by/3.0/
*/ -->
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Boutique</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,600,700" rel="stylesheet" />
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    <!-- font Awesome-->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <!-- gLightbox gallery-->
    <link rel="stylesheet" href="{% static 'vendor/glightbox/css/glightbox.min.css' %}">
    <!-- Range slider-->
    <link rel="stylesheet" href="{% static 'vendor/nouislider/nouislider.min.css' %}">
    <!-- Choices CSS-->
    <link rel="stylesheet" href="{% static 'vendor/choices.js/public/assets/styles/choices.min.css' %}">
    <!-- Swiper slider-->
    <link rel="stylesheet" href="{% static 'vendor/swiper/swiper-bundle.min.css' %}">
    <!-- Google fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/favicon.png">
  </head>
  <body>
    <div class="page-holder">
      <!-- navbar-->
      <header class="header bg-white">
        <div class="container px-lg-3">
          <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0"><a class="navbar-brand" href="index.html"><span class="fw-bold text-uppercase text-dark">Boutique</span></a>
            <button class="navbar-toggler navbar-toggler-end" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <!-- Link--><a class="nav-link active" href="index.html">Home</a>
                </li>
                <li class="nav-item">
                  <!-- Link--><a class="nav-link" href="{% url 'core:product-list' %}">Shop</a>
                </li>
                <li class="nav-item">
                  <!-- Link--><a class="nav-link" href="detail.html">Product detail</a>
                </li>
                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pages</a>
                  <div class="dropdown-menu mt-3 shadow-sm" aria-labelledby="pagesDropdown"><a class="dropdown-item border-0 transition-link" href="index.html">Homepage</a><a class="dropdown-item border-0 transition-link" href="detail.html">Product detail</a><a class="dropdown-item border-0 transition-link" href="cart.html">Shopping cart</a><a class="dropdown-item border-0 transition-link" href="checkout.html">Checkout</a></div>
                </li>
               
                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
					<div class="dropdown-menu mt-3 shadow-sm" aria-labelledby="pagesDropdown">
            {% for c in categories %}
            <a class="dropdown-item border-0 transition-link" href="{% url 'core:product-category-list' c.cid %}"><img class="rounded-circle" width="37px" height="37px" src="{{c.image.url}}" style="max-width: 100px;max-height: 150px;"/>{{c.title}}</a>
          	{% endfor %}
          </div>
               </li>
				
              </ul>
              <ul class="navbar-nav ms-auto">               
                <li class="nav-item"><a class="nav-link" href="cart.html"> <i class="fas fa-dolly-flatbed me-1 text-gray"></i>Cart<small class="text-gray fw-normal">(2)</small></a></li>
                <li class="nav-item"><a class="nav-link" href="#!"> <i class="far fa-heart me-1"></i><small class="text-gray fw-normal"> (0)</small></a></li>
                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="" data-bs-toggle="dropdown"  aria-haspopup="true" aria-expanded="false"> <i class="fas fa-user me-1 text-gray fw-normal"></i>User</a>
					<div class="dropdown-menu mt-3 shadow-sm" aria-labelledby="pagesDropdown"><a class="dropdown-item border-0 transition-link" href="/user/profile/">My Account</a><a class="dropdown-item border-0 transition-link" href="shop.html">Order tracking</a><a class="dropdown-item border-0 transition-link" href="detail.html">My wishlist</a><a class="dropdown-item border-0 transition-link" href="cart.html">Setting</a>
						{% if request.user.is_authenticated %}
						<a class="dropdown-item border-0 transition-link"  href="{% url 'userauths:sign-out' %}">Sign out</a>
						{% else %}
						<a class="dropdown-item border-0 transition-link"  href="{% url 'userauths:sign-in' %}">Sign in</a>
						{% endif %}
					</div>
          
				</li>
              </ul>
              
            </div>
          </nav>
          <form class="p-2 rounded shadow-sm bg-white" action="{% url 'core:search' %}" method="GET">
            <div class="input-group">
              <input class="form-control border-0 me-2 shadow-0" type="search" placeholder="Search for items..." name="q">
              <button class="btn btn-primary rounded" type="submit"><i class="fas fa-search"></i></button>
            </div>
          </form>
        </div>

      </header>	{% if messages %}
				  {% for message in messages %}
				  <div class="alert alert-{{message.tags}}">
					<strong>{{message}}</strong>
				</div>
				  {% endfor %}
		{% endif %}
		<script>
			 setTimeout(() => {
                $(".alert").alert("close")
			 },4000)
		</script>
      <!--  Modal -->
	  {% block content %}

	  {% endblock content %}
	
      <footer class="bg-dark text-white">
        <div class="container py-4">
          <div class="row py-5">
            <div class="col-md-4 mb-3 mb-md-0">
              <h6 class="text-uppercase mb-3">Customer services</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="/user/contact/">Help &amp; Contact Us</a></li>
                <li><a class="footer-link" href="#!">Returns &amp; Refunds</a></li>
                <li><a class="footer-link" href="#!">Online Stores</a></li>
                <li><a class="footer-link" href="#!">Terms &amp; Conditions</a></li>
              </ul>
            </div>
            <div class="col-md-4 mb-3 mb-md-0">
              <h6 class="text-uppercase mb-3">Company</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="#!">What We Do</a></li>
                <li><a class="footer-link" href="#!">Available Services</a></li>
                <li><a class="footer-link" href="#!">Latest Posts</a></li>
                <li><a class="footer-link" href="#!">FAQs</a></li>
              </ul>
            </div>
            <div class="col-md-4">
              <h6 class="text-uppercase mb-3">Social media</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="#!">Twitter</a></li>
                <li><a class="footer-link" href="#!">Instagram</a></li>
                <li><a class="footer-link" href="#!">Tumblr</a></li>
                <li><a class="footer-link" href="#!">Pinterest</a></li>
              </ul>
            </div>
          </div>
          <div class="border-top pt-4" style="border-color: #1d1d1d !important">
            <div class="row">
              <div class="col-md-6 text-center text-md-start">
                <p class="small text-muted mb-0">&copy; 2023 All rights reserved.</p>
              </div>
              <div class="col-md-6 text-center text-md-end">
                <p class="small text-muted mb-0">Template designed by <a class="text-white reset-anchor" href="https://bootstrapious.com/p/boutique-bootstrap-e-commerce-template">Nevissa</a></p>
                <!-- If you want to remove the backlink, please purchase the Attribution-Free License. See details in readme.txt or license.txt. Thanks!-->
              </div>
            </div>
          </div>
        </div>
      </footer>
      
      <!-- JavaScript files-->
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
      <script src="{% static 'vendor/nouislider/nouislider.min.js' %}"></script>
      <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
      <script src="{% static 'vendor/choices.js/public/assets/scripts/choices.min.js' %}"></script>
      <script src="{% static 'js/front.js' %}"></script>
      <script src="{% static 'js/function.js' %}"></script>
      <script>
         // ------------------------------------------------------- //
        //   Inject SVG Sprite - 
        //   see more here 
        //   https://css-tricks.com/ajaxing-svg-sprite/
        // ------------------------------------------------------ //
        function injectSvgSprite(path) {
        
            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function(e) {
            var div = document.createElement("div");
            div.className = 'd-none';
            div.innerHTML = ajax.responseText;
            document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }
 
        // this is set to BootstrapTemple website as you cannot 
        // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
        // while using file:// protocol
        // pls don't forget to change to your domain :)
        injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg'); 
        
      </script>
      <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </div>
  </body>
</html>