core/urls.py
from django.urls import path
from core.views import product_list_view,category_list_view,product_category_list_view,seller_list_view,seller_detail_view,product_detail_view,tag_list, ajax_add_review,search_view,index

app_name= "core"

urlpatterns = [

    #HomePage
    path('',index,name='index'),

    #Products
    path("products/",product_list_view,name="product-list"),
    path("products/<pid>",product_detail_view,name="product-detail"),

    #Categories
    path("category/",category_list_view,name="category-list"),
    path("category/<cid>/",product_category_list_view,name="product-category-list"),
    
    #Seller
    path("seller/",seller_list_view,name="seller-list"),
    path("seller/<sid>/",seller_detail_view,name="seller-detail"),

    #Tags
    path("products/tag/<slug:tag_slug>/",tag_list,name="tag"),

    #Reviews
    path("ajax-add-review/<pid>/", ajax_add_review, name="ajax-add-review"),

    #Search
    path("search/",search_view, name="search")

]                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

ecommerceprojet2/urls.py
from django.contrib import admin
from django.urls import path ,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)      

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)      

core/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.safestring import mark_safe
from userauths.models import User
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField

STATUS_CHOICE = (
    ("process", "Processing"),
    ("shipped", "Shipped"),
    ("delivered", "Delivered"),
)

STATUS = (
    ("draft", "Draft"),
    ("diasbled", "Disabled"),
    ("rejected", "Rejected"),
    ("in_review", "In_Review"),
    ("published", "Published"),
)


RATING = (
    (1, "★☆☆☆☆"),
    (2, "★★☆☆☆"),
    (3, "★★★☆☆"),
    (4, "★★★★☆"),
    (5, "★★★★★"),
)




def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)
# Create your models here.

class Category(models.Model):
    cid = ShortUUIDField(unique=True,length=10, max_length=20, prefix="cat", alphabet="abcd1234567")
    title = models.CharField(max_length=100, default="Furniture")
    image = models.ImageField(upload_to="category", default="")

    class Meta:
        verbose_name_plural = "Categories"
    
    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' % (self.image.url))
    
    def __str__(self):
        return self.title

class Seller(models.Model):
     sid = ShortUUIDField(unique=True  ,length=10, max_length=30, prefix="sel", alphabet="abcdfegh1234567")
     title = models.CharField(max_length=100, default="Furni")
     image = models.ImageField(upload_to="user_directory_Path", default="seller.jpg")
     cover_image = models.ImageField(upload_to="user_directory_Path", default="seller.jpg")
    #  description = models.TextField(null=True, blank="Amazing Seller")
     description = RichTextUploadingField(null=True, blank="Amazing Seller")
     adress = models.CharField(max_length=100, default="1234 ADRESSS")
     contact = models.CharField(max_length=100, default="+123 (456) 789")
     chat_resp_time = models.CharField(max_length=100, default="100")
     shipping_on_time = models.CharField(max_length=100, default="100")
     authentic_rating = models.CharField(max_length=100, default="100")
     days_return = models.CharField(max_length=100, default="100")
     warranty_period = models.CharField(max_length=100, default="100")
     date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    #CASCADE

     user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

     class Meta:
        verbose_name_plural = "Sellers"
    
     def seller_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' % (self.image.url))
    
     def __str__(self):
        return self.title

class Tags(models.Model):
    pass
     
class Product(models.Model):
     pid = ShortUUIDField(unique=True,length=10, max_length=30, prefix="prd", alphabet="abcdfegh1234567")

     user = models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
     category = models.ForeignKey(Category,on_delete=models.SET_NULL, null=True, related_name="category")
     seller = models.ForeignKey(Seller,on_delete=models.SET_NULL, null=True, related_name="product")

     title = models.CharField(max_length=100,default="Nice")
     image = models.ImageField(upload_to="user_directory_Path", default="product.jpg")
    #  description = models.TextField(null=True, blank="this is the product")
     description =RichTextUploadingField(null=True, blank="this is the product")
     price = models.DecimalField(max_digits=999999999999, decimal_places=2, default="1,99")
     old_price = models.DecimalField(max_digits=999999999999, decimal_places=2, default="2,99")


    #  specifications = models.TextField( null=True, blank=True)
     specifications = RichTextUploadingField( null=True, blank=True)
     title = models.CharField(max_length=100,default="Nice",null=True, blank=True)
     stock_count = models.CharField(max_length=100,default="10", null=True, blank=True)
     expire_day = models.CharField(max_length=100,default="100 Days",  null=True, blank=True)
     produced = models.DateTimeField(auto_now_add=False, null=True, blank=True)
     # tags = models.ForeignKey(Tags, on_delete=models.SET_NULL, null=True)
     tags = TaggableManager(blank=True)

     product_status = models.CharField(choices=STATUS, max_length=10, default="in_review")

     status = models.BooleanField(default=True)
     in_stock = models.BooleanField(default=True)
     featured = models.BooleanField(default=False)
     digital = models.BooleanField(default=False)
     
     sku = ShortUUIDField(unique=True,length=4, max_length=10, prefix="sku", alphabet="1234567890")

     date = models.DateTimeField(auto_now_add=True)
     updated = models.DateTimeField(null=True, blank=True)

  
     class Meta:
        verbose_name_plural = "Products"
    
     def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' % (self.image.url))
    
     def __str__(self):
        return self.title
     
     def get_percentage(self):
        new_price = (self.price / self.old_price) * 100
        return new_price


class ProductImages(models.Model):
    images = models.ImageField(upload_to="product-images", default="product.jpg")
    product = models.ForeignKey(Product, related_name="product_images", on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Product Images"
  

class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=999999999999, decimal_places=2, default="1,99")
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(choices=STATUS_CHOICE, max_length=30, default="processing")

    class Meta:
        verbose_name_plural = "Cart Order"
  


class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    product_status = models.CharField(max_length=200)
    invoice_no = models.CharField(max_length=200)
    item = models.CharField(max_length=200)
    image =models.CharField(max_length=200)
    quantity = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=999999999999, decimal_places=2, default="1,99")
    total = models.DecimalField(max_digits=999999999999, decimal_places=2, default="1,99")
  
    class Meta:
        verbose_name_plural = "Cart Order Items"


    def order_image(self):
        return mark_safe('<img src="/media/%s" width="50" height="50"/>' % (self.image))
    


class  ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True,related_name="reviews" )
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)
        
    class Meta:
           verbose_name_plural = "Product Reviews"

    def __str__(self):
           return self.product.title
    
    def get_rating(self):
            return self.rating
        
class wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL,null=True)
    date = models.DateTimeField(auto_now_add=True)
        
    class Meta:
           verbose_name_plural = "wishlists"

    def __str__(self):
           return self.product.title    
    
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    address = models.CharField(max_length=100, null=True)
    status = models.BooleanField(default=True)    

    class Meta:
       verbose_name_plural = "Address"

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':"Write review"}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from math import prod
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render,get_object_or_404
from django.db.models import Count,Avg
from taggit.models import Tag

from core.models import Product, Category, Seller, CartOrder, CartOrderItems, ProductImages, ProductReview, wishlist,Address
from core.forms import ProductReviewForm
 
# Create your views here.

def index(request):
    products = Product.objects.filter(product_status="published",featured=True)

    context = {
        "products":products
    }
    return render(request,'core/index.html',context)

def product_list_view(request):
    products = Product.objects.filter(product_status="published")

    context = {
        "products":products
    }
    return render(request,'core/product-list.html',context)

def category_list_view(request):
    categories = Category.objects.all()

    context = {
        "categories":categories
    }
    return render(request,'core/category-list.html',context)


def product_category_list_view(request,cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status="published", category=category)

    context = {
        "category":category,
        "products":products,
    }
    return render(request,'core/product-category-list.html',context)

def seller_list_view(request):
    sellers = Seller.objects.all()
    context = {
        "sellers":sellers,
    }
    return render(request, "core/seller-list.html",context)

def seller_detail_view(request,sid):
    seller = Seller.objects.get(sid=sid)
    products = Product.objects.filter(seller=seller,product_status="published")
    context = {
        "seller":seller,
        "products":products,
    }
    return render(request, "core/seller-detail.html",context)

def product_detail_view(request,pid):
    product = Product.objects.get(pid=pid)
    product_images = product.product_images.all()
    product_cat = Product.objects.filter(category=product.category).exclude(pid=pid)
    reviews = ProductReview.objects.filter(product=product).order_by("-date")
    avg_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    review_form = ProductReviewForm()
    make_review= True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()

        if user_review_count > 0:
            make_review = False
    context = {
        "product":product,
        "product_images":product_images,
        "product_cat":product_cat,
        "reviews":reviews,
        "avg_rating":avg_rating,
        "review_form":review_form,
        "make_review":make_review,
    }
    return render(request, "core/product-detail.html",context)

def tag_list(request,tag_slug=None):
    products=Product.objects.filter(product_status="published").order_by("-id")

    tag=None
    if tag_slug:
      tag=get_object_or_404(Tag, slug=tag_slug)
      products = products.filter(tags__in=[tag])
    
    context ={
        "products": products,
        "tag": tag
    } 
    return render(request, "core/tag.html", context)

def ajax_add_review(request,pid):
    product = Product.objects.get(pid=pid)
    user = request.user

    review = ProductReview.objects.create(
        user=user,
        product=product,
        review=request.POST['review'],
        rating=request.POST['rating'],
    )

    context = {
        'user': user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],
    }

    avg_reviews= ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))

    return JsonResponse(
        {
        'bool': True,
        'context': context,
        'avg_reviews': avg_reviews,
        }
    )

def search_view(request):
    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains=query).order_by("-date")
 
    context = {
        "products": products,
        "query": query,
        
    }
    return render(request, "core/search.html", context)

templates/core/category-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <!--  Modal -->
    <div class="modal fade" id="productView" tabindex="-1">
      <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content overflow-hidden border-0">
          <button class="btn-close p-4 position-absolute top-0 end-0 z-index-20 shadow-0" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
          <div class="modal-body p-0">
            <div class="row align-items-stretch">
              <div class="col-lg-6 p-lg-0"><a class="glightbox product-view d-block h-100 bg-cover bg-center" style="background: url(/static/img/product-5.jpg)" data-gallery="gallery1" data-glightbox="Red digital smartwatch"></a><a class="glightbox d-none" href="img/product-5-alt-1.jpg" data-gallery="gallery1" data-glightbox="Red digital smartwatch"></a><a class="glightbox d-none" href="img/product-5-alt-2.jpg" data-gallery="gallery1" data-glightbox="Red digital smartwatch"></a></div>
              <div class="col-lg-6">
                <div class="p-4 my-md-4">
                  <ul class="list-inline mb-2">
                    <li class="list-inline-item m-0"><i class="fas fa-star small text-warning"></i></li>
                    <li class="list-inline-item m-0 1"><i class="fas fa-star small text-warning"></i></li>
                    <li class="list-inline-item m-0 2"><i class="fas fa-star small text-warning"></i></li>
                    <li class="list-inline-item m-0 3"><i class="fas fa-star small text-warning"></i></li>
                    <li class="list-inline-item m-0 4"><i class="fas fa-star small text-warning"></i></li>
                  </ul>
                  <h2 class="h4">Red digital smartwatch</h2>
                  <p class="text-muted">$250</p>
                  <p class="text-sm mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.</p>
                  <div class="row align-items-stretch mb-4 gx-0">
                    <div class="col-sm-7">
                      <div class="border d-flex align-items-center justify-content-between py-1 px-3"><span class="small text-uppercase text-gray mr-4 no-select">Quantity</span>
                        <div class="quantity">
                          <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button>
                          <input class="form-control border-0 shadow-0 p-0" type="text" value="1">
                          <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-5"><a class="btn btn-dark btn-sm w-100 h-100 d-flex align-items-center justify-content-center px-0" href="cart.html">Add to cart</a></div>
                  </div><a class="btn btn-link text-dark text-decoration-none p-0" href="#!"><i class="far fa-heart me-2"></i>Add to wish list</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <!-- HERO SECTION-->
      <section class="py-5 bg-light">
        <div class="container">
          <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
            <div class="col-lg-6">
              <h1 class="h2 text-uppercase mb-0">Shop</h1>
            </div>
            <div class="col-lg-6 text-lg-end">
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-lg-end mb-0 px-0 bg-light">
                  <li class="breadcrumb-item"><a class="text-dark" href="index.html">Home</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Shop</li>
                </ol>
              </nav>
            </div>
          </div>
        </div>
      </section>
      <section class="py-5">
        <div class="container p-0">
          <div class="row">
            <!-- SHOP SIDEBAR-->
            <div class="col-lg-3 order-2 order-lg-1">
              <h5 class="text-uppercase mb-4">Categories</h5>
             
              {% for c in categories %}
              
              <div class="py-2 px-4 bg-dark text-white mb-3 category-item"><strong class="small text-uppercase fw-bold"><img  class="rounded-circle" width="37px" height="37px" src="{{  c.image.url }}">{{ c.title }}</a><span class="badge badge-primary badge-pill">{{ c.category.count }}</span></strong></div>
             
              </ul>
              {% endfor %}
              <h6 class="text-uppercase mb-4">Price range</h6>
              <div class="price-range pt-4 mb-5">
                <div id="range"></div>
                <div class="row pt-2">
                  <div class="col-6"><strong class="small fw-bold text-uppercase">From</strong></div>
                  <div class="col-6 text-end"><strong class="small fw-bold text-uppercase">To</strong></div>
                </div>
              </div>
              <h6 class="text-uppercase mb-3">Show only</h6>
              <div class="form-check mb-1">
                <input class="form-check-input" type="checkbox" id="checkbox_1">
                <label class="form-check-label" for="checkbox_1">Returns Accepted</label>
              </div>
              <div class="form-check mb-1">
                <input class="form-check-input" type="checkbox" id="checkbox_2">
                <label class="form-check-label" for="checkbox_2">Returns Accepted</label>
              </div>
              <div class="form-check mb-1">
                <input class="form-check-input" type="checkbox" id="checkbox_3">
                <label class="form-check-label" for="checkbox_3">Completed Items</label>
              </div>
              <div class="form-check mb-1">
                <input class="form-check-input" type="checkbox" id="checkbox_4">
                <label class="form-check-label" for="checkbox_4">Sold Items</label>
              </div>
              <div class="form-check mb-1">
                <input class="form-check-input" type="checkbox" id="checkbox_5">
                <label class="form-check-label" for="checkbox_5">Deals &amp; Savings</label>
              </div>
              <div class="form-check mb-4">
                <input class="form-check-input" type="checkbox" id="checkbox_6">
                <label class="form-check-label" for="checkbox_6">Authorized Seller</label>
              </div>
              <h6 class="text-uppercase mb-3">Buying format</h6>
              <div class="form-check mb-1">
                <input class="form-check-input" type="radio" name="customRadio" id="radio_1">
                <label class="form-check-label" for="radio_1">All Listings</label>
              </div>
              <div class="form-check mb-1">
                <input class="form-check-input" type="radio" name="customRadio" id="radio_2">
                <label class="form-check-label" for="radio_2">Best Offer</label>
              </div>
              <div class="form-check mb-1">
                <input class="form-check-input" type="radio" name="customRadio" id="radio_3">
                <label class="form-check-label" for="radio_3">Auction</label>
              </div>
              <div class="form-check mb-1">
                <input class="form-check-input" type="radio" name="customRadio" id="radio_4">
                <label class="form-check-label" for="radio_4">Buy It Now</label>
              </div>
            </div>
            <!-- SHOP LISTING-->
            <div class="col-lg-9 order-1 order-lg-2 mb-5 mb-lg-0">
              <div class="row mb-3 align-items-center">
                <div class="col-lg-6 mb-2 mb-lg-0">
                  <p class="text-sm text-muted mb-0">Showing 1–12 of 53 results</p>
                </div>
                <div class="col-lg-6">
                  <ul class="list-inline d-flex align-items-center justify-content-lg-end mb-0">
                    <li class="list-inline-item text-muted me-3"><a class="reset-anchor p-0" href="#!"><i class="fas fa-th-large"></i></a></li>
                    <li class="list-inline-item text-muted me-3"><a class="reset-anchor p-0" href="#!"><i class="fas fa-th"></i></a></li>
                    <li class="list-inline-item">
                      <select class="selectpicker" data-customclass="form-control form-control-sm">
                        <option value>Sort By </option>
                        <option value="default">Default sorting </option>
                        <option value="popularity">Popularity </option>
                        <option value="low-high">Price: Low to High </option>
                        <option value="high-low">Price: High to Low </option>
                      </select>
                    </li>
                  </ul>
                </div>
              </div>
             <!-- CATEGORIES SECTION-->
	<section class="pt-5">
        <header class="text-center">
          <p class="small text-muted small text-uppercase mb-1">Carefully created collections</p>
          <h2 class="h5 text-uppercase mb-4">Browse our categories</h2>
          <h2 class="text-warning">
            {{ categories.count}} Categories
        </h2>
        </header>

        <div class="row">
            
		{% for c in categories %}
          <div class="col-md-4">
            <a  class="category-item" href="{% url 'core:product-category-list' c.cid %}"><img class="img-fluid" src="{{c.image.url}}" alt="" href="{% url 'core:product-category-list' c.cid %}"/><strong class="category-item-title">{{ c.title }}</strong></a>
            <p class="mr-10 text-center text-info">{{ c.category.count }} Product{{ c.category.count|pluralize}} </p>
          </div>
        {% endfor %}
        </div>
      </section>
              <!-- PAGINATION-->
              <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center justify-content-lg-end">
                  <li class="page-item mx-1"><a class="page-link" href="#!" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                  <li class="page-item mx-1 active"><a class="page-link" href="#!">1</a></li>
                  <li class="page-item mx-1"><a class="page-link" href="#!">2</a></li>
                  <li class="page-item mx-1"><a class="page-link" href="#!">3</a></li>
                  <li class="page-item ms-1"><a class="page-link" href="#!" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </section>
    </div>



{% endblock content %}

templates/core/seller-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

  <!-- Hero section-->
  <section class="hero-home py-5">
    <div class="container pt-5">
      <div class="row">
        <div class="col-lg-7 mx-auto text-center">
          <p class="h6 text-uppercase text-primary mb-3">Sellers list</p>
          <h1 class="mb-5">A curated directory of tools and resources to build your startup.</h1>
          <p class="h6 text-uppercase text-primary mb-3">We own {{sellers.count}} seller{{sellers.count|pluralize}} untill now!</p>
          <form class="p-2 rounded shadow-sm bg-white" action="#!">
            <div class="input-group">
              <input class="form-control border-0 me-2 shadow-0" type="search" placeholder="Search tools and resources...">
              <button class="btn btn-primary rounded" type="submit"><i class="fas fa-search"></i></button>
            </div>
          </form>
        </div>
        </div>
    </div>
  </section>
  <!-- Features section-->
  
  <div class="container py-5">
    

    <!-- For demo purpose -->
    <div class="row text-center text-white mb-5">
      <div class="col-lg-7 mx-auto">
        <h1 class="display-4">Bootstrap 4 list</h1>
        <p class="lead mb-0">Create an elegant product list using Bootstrap 4 list group</p>
        <p class="lead">Snippet by <a href="https://bootstrapious.com/snippets" class="text-white"> 
                  <u>Bootstrapious</u></a>
        </p>
      </div>
    </div>
    <!-- End -->
  
    <div class="row">
      {% for s in sellers %}
      <div class="col-lg-6 col-md-6 col-12 col-sm-6  ">
  
        <!-- List group-->
        <ul class="list-group shadow">
  
          <!-- list group item-->
          <li class="list-group-item">
            <!-- Custom content-->
            <div class="media align-items-lg-center flex-column flex-lg-row p-3 ">
              <div class="media-body order-2 order-lg-1">
                <h5 class="mt-0 font-weight-bold mb-2">{{s.title}}</h5>
                <div class="badge text-white bg-primary">{{s.adress}}</div>
                <div class="badge text-white bg-secondary">{{s.contact}}</div>
                <div class="badge text-white bg-info">since {{s.date|date:"Y"}}</div>
                <p class="font-italic text-muted mb-0 small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit fuga autem maiores necessitatibus.</p>
                <div class="d-flex align-items-center justify-content-between mt-1">
                  <h6 class="font-weight-bold my-2">{{s.product.all.count}}products</h6>
                  <ul class="list-inline small">
                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                    <li class="list-inline-item m-0"><i class="fa fa-star-o text-gray"></i></li>
                  </ul>
                </div>
              </div>
              
              <img src="{{s.image.url}}" alt="Generic placeholder image" width="200" class="ml-lg-5 order-1 order-lg-2" href="{% url 'core:seller-detail' s.sid %}">
              
                  <span> <a class="btn btn-sm btn-outline-dark" href="{% url 'core:seller-detail' s.sid %}">View Detail</a></span>
                  
            </div>
            <!-- End -->
          </li>
          <!-- End -->
          
  
         
  
        </ul>
        <!-- End -->
      </div>
      {% endfor %}
    </div>
    
  </div>
  
{% endblock content %}